export enum Roles {
  SYSTEM_ADMIN = 'SystemAdmin',
  CENTER_ADMIN = 'CenterAdmin',
  INSPECTOR = 'Inspector',
  INSPECTION_APPROVER = 'InspectionApprover',
  INSPECTION_APPROVER_MANAGER = 'InspectionApproverManager',
  HELPDESK = 'HelpDesk',
  HELPDESKADMIN = 'HelpDeskAdmin',
  FIELD_SUPPORTER = 'FieldSupporter',
  FIELD_SUPPORT_MANAGER = 'FieldSupportManager',
  APPEAL_REVIEWER = 'AppealReviewer',
  SYSTEM_MANAGER = 'SystemManager',
  SURVEYOR_MANAGER = 'SurveyorManager',
  SURVEYOR = 'Surveyor',
  EMERGENCY_MANAGER = 'EmergencyManager',
  FINANCE_ADMIN = 'FinanceAdmin',
  FINANCE_OFFICER = 'FinanceOfficer',
  APPEALCOMMITTEE = 'AppealCommittee',
  CLOSE_REVIEW_USER = "CloseReviewUser",
  EMERGENCY_INSPECTOR = "EmergencyInspector"
}
